[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[cmd_duration]
min_time = 5000
show_notifications = true

[aws]
style = "bold yellow"
displayed_items = "all"
symbol = "ğŸ§‡ "

[hostname]
ssh_only = true
